### ISSUE TITLE
Simple form / post demo

### ISSUE THREAD

**Issue by leus** [UdashFramework/udash-demos#11]
I'm having a really hard time to justify investing more time in this framework, which is a shame because it looks really cool. My main problem is the lack of documentation and completely inadequacy of sample code.

Can you guys put a couple of examples on how to perform a simple form submission, doing something server side and show the results back in a different view? I've been many hours trying to accomplish this seemingly simple task.

(By the way, I've been trying really hard to come up with such an example but to no avail).

**Comment by Starzu** [comment]
Did you try the `todo-rpc` demo or an application setup from the [Giter8 template](https://github.com/UdashFramework/udash.g8)?

The `todo-rpc` demo is an example of working very close to the raw HTML - that is one of our objectives to allow users to write raw HTML when they want. 
The application generated from the template uses Bootstrap 3 wrapper (or Bootstrap 4 from the branch named `bootstrap4`, but it's still in development). You can find an example login page with a server-side authentication - take a look at `LoginPageView` class.

**Comment by leus** [comment]
Yes, I have look, downloaded, and tried to modify all of those to work as I need. 

Take the todo-rpc application, for instance, since is the one closer to what I need. It is a single page application; I don't get to see how a "normal" CRUD operation is to be performed, or a table displaying rows from a database.

The Giter8 template is that one with a chat and a weird login authentication that changes every time you refreshes it? The one with the inconsistent rpc naming between packages? That's the one that lost six of us for one complete day trying to make it work. We managed to add a page with two input boxes and a table that did absolutely nothing.

Guys, this looks like an incredible piece of tech. But it's introductory examples are so far removed from every day use that's not funny. We are a team of backend developers, we work with Scala and petabytes of data every day, yet six of us couldn't manage to make a simple form work. I usually just agree that I'm kind of dumb, but I doubt the six other guys are as dumb as myself. We were in a hackaton and we just needed to slap a basic html interface in front of some Spark generated magic. We lost the entire day fighting with this; incredulity was the main culprit because we just couldn't believe this would be so hard and we didn't bail out earlier that day. At the end I just slapped a web interface in a completely different language in 10 minutes - life is too short to keep banging at walls.

(I'm still trying to make this work in my spare time because I think this is the right framework for Scala. But at work we will use something else).

Anyways, if simpler examples are not in your list of priorities, feel free to close this.

**Comment by Starzu** [comment]
What about the `rest-akka`http` demo? It's an example of application with CRUD operations - it uses REST as client-server communication method, but you can find there forms, tables and three views. 

Generally speaking I agree that we need more examples and we should improve the guide. If you want to contribute, feel free to create a PR with a new demo - I'll be happy to help you with implementation.
